### ISSUE TITLE
EC2 discovery error 

### ISSUE THREAD

**Issue by arthur-c** [hazelcast/hazelcast-docker#1]
Hi,

I'm trying to boot 2 dockers on 2 Coreos nodes with aws auto-discovery but I get this stacktrace : 

```
g 11 09:05:18 coreos-worker-01 docker[1213]: Digest: sha256:38838ae69d4ca5cae6d5e156ba1ed525f8a76ecd4e9a1e57b86946e943785125
Aug 11 09:05:19 coreos-worker-01 systemd[1]: Started Hazelcast OSS.
Aug 11 09:05:22 coreos-worker-01 docker[1342]: Aug 11, 2015 9:05:22 AM com.hazelcast.config.XmlConfigLocator
Aug 11 09:05:22 coreos-worker-01 docker[1342]: INFO: Loading 'hazelcast.xml' from working directory.
Aug 11 09:05:22 coreos-worker-01 docker[1342]: Aug 11, 2015 9:05:22 AM com.hazelcast.instance.DefaultAddressPicker
Aug 11 09:05:23 coreos-worker-01 docker[1342]: INFO: [LOCAL] [dev] [3.5] Prefer IPv4 stack is true.
Aug 11 09:05:23 coreos-worker-01 docker[1342]: Aug 11, 2015 9:05:23 AM com.hazelcast.instance.DefaultAddressPicker
Aug 11 09:05:23 coreos-worker-01 docker[1342]: INFO: [LOCAL] [dev] [3.5] Picked Address[172.32.78.2]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Aug 11 09:05:23 coreos-worker-01 docker[1342]: Aug 11, 2015 9:05:23 AM com.hazelcast.spi.OperationService
Aug 11 09:05:23 coreos-worker-01 docker[1342]: INFO: [172.32.78.2]:5701 [dev] [3.5] Backpressure is disabled
Aug 11 09:05:23 coreos-worker-01 docker[1342]: Aug 11, 2015 9:05:23 AM com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor
Aug 11 09:05:23 coreos-worker-01 docker[1342]: INFO: [172.32.78.2]:5701 [dev] [3.5] Starting with 2 generic operation threads and 2 partition operation threads.
Aug 11 09:05:23 coreos-worker-01 docker[1342]: Aug 11, 2015 9:05:23 AM com.hazelcast.system
Aug 11 09:05:23 coreos-worker-01 docker[1342]: INFO: [172.32.78.2]:5701 [dev] [3.5] Hazelcast 3.5 (20150617 - 4270dc6) starting at Address[172.32.78.2]:5701
Aug 11 09:05:23 coreos-worker-01 docker[1342]: Aug 11, 2015 9:05:23 AM com.hazelcast.system
Aug 11 09:05:23 coreos-worker-01 docker[1342]: INFO: [172.32.78.2]:5701 [dev] [3.5] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved.
Aug 11 09:05:23 coreos-worker-01 docker[1342]: Aug 11, 2015 9:05:23 AM com.hazelcast.instance.Node
Aug 11 09:05:23 coreos-worker-01 docker[1342]: INFO: [172.32.78.2]:5701 [dev] [3.5] Creating AWSJoiner
Aug 11 09:05:23 coreos-worker-01 docker[1342]: Exception in thread "main" com.hazelcast.core.HazelcastException: java.lang.ClassNotFoundException: com.hazelcast.cluster.impl.TcpIpJoinerOverAWS
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:67)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.instance.Node.createJoiner(Node.java:568)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.instance.DefaultNodeContext.createJoiner(DefaultNodeContext.java:35)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.instance.Node.<init>(Node.java:171)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:120)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.core.server.StartServer.main(StartServer.java:36)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: Caused by: java.lang.ClassNotFoundException: com.hazelcast.cluster.impl.TcpIpJoinerOverAWS
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at java.security.AccessController.doPrivileged(Native Method)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at java.lang.Class.forName0(Native Method)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at java.lang.Class.forName(Class.java:191)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: at com.hazelcast.instance.Node.createJoiner(Node.java:564)
Aug 11 09:05:23 coreos-worker-01 docker[1342]: ... 8 more
```

The aws part in my hazelcast.xml:
```
            <aws enabled="true">
                <access-key>AKIAIXXX</access-key>
                <secret-key>XXX</secret-key>
                <!--optional, default is us-east-1 -->
                <region>us-east-1</region>
                <!--optional, default is ec2.amazonaws.com. If set, region shouldn't be set as it will override this property -->
              <!--  <host-header>ec2.amazonaws.com</host-header> -->
                <!-- optional, only instances belonging to this group will be discovered, default will try all running instances -->
              <!--  <security-group-name>default</security-group-name> -->
            </aws>
 ```
and the complete xml: https://gist.github.com/arthur-c/e3ed7d9b8f90aeb12a4e

My Dockerfile:

```
FROM hazelcast/hazelcast:latest
# Add your custom hazelcast.xml
ADD hazelcast.xml $HZ_HOME
# Run hazelcast
CMD java -cp $HZ_HOME/hazelcast-$HZ_VERSION.jar com.hazelcast.core.server.StartServer
```

I'm not sure if there is a relation with this bug : https://github.com/hazelcast/hazelcast/issues/5653

**Comment by jarosite** [comment]
error is java.lang.ClassNotFoundException: com.hazelcast.cluster.impl.TcpIpJoinerOverAWS wich means that file hazelcast-$HZ_VERSION.jar missed cloud implementation, this topic should clarify what to do http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#discovering-members-within-ec2-cloud

**Comment by eminn** [comment]
The default hazelcast.jar does not contain the classes for ec2 discovery, which are located in hazelcast-cloud.jar. We can make docker images to use hazelcast-all.jar which includes all modules of the hazelcast.

**Comment by jarosite** [comment]
would be nice

**Comment by bilalyasar** [comment]
@arthur-c , @jarosite  i made a little fix. If you have chance, can you try again?
Also in your xml you need to provide your ec2 private address. 
```
    <network>
	<public-address>EC2_PRIVATE_ADDRESS</public-address>
...
...
    </network>
```

**Comment by arthur-c** [comment]
Hi,

I will try this as soon as possible (in hollidays currently ).

Thanks,

A.

**Comment by arthur-c** [comment]
Thanks for the tips. I added the needed jar, changed my dockerfile CMD to 
```
CMD java -cp $HZ_HOME/hazelcast-all-$HZ_VERSION.jar com.hazelcast.core.server.StartServer
```
and it works a little better, I'm able to telnet to 5701 and see the connection in hazelcast log.

But I got this error when a node discover the other node:

```
Sep 02, 2015 10:57:42 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
WARNING: [172.32.42.5]:5701 [dev] [3.5.2] Wrong bind request from Address[172.32.59.3]:5701! This node is not requested endpoint: Address[172.31.71.180]:5701
Sep 02, 2015 10:57:42 AM com.hazelcast.nio.tcp.TcpIpConnection
```

It's probably because I didn't set <public-address>EC2_PRIVATE_ADDRESS</public-address>
My container IP is dynamically set when the container starts with flannel, I only know the network subnet and range.
Is there a way to avoid the endpoint definition, ec2 private ip and allow a full dynamic discovery ?

**Comment by bilalyasar** [comment]
@arthur-c currently we don't support full dynamic discovery.
But you can give your private ip addresses as command line argument while running your image..

Here is a trick that i used before:

this was my run script that adds command line arguments to tomcat environment:
https://github.com/hazelcast/hazelcast-docker/blob/session-replication/run.sh

and in hazelcast.xml we are supporting environment variables
this is an example: 
http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#using-variables

my docker run command was: `sudo docker run -it –rm -p 8080:8080 -p 5701:5701 -e public_ip=MACHINE_1_IP -e member1=MACHINE_1_IP -e member2=MACHINE_2_IP -e name=member1 hazelcast/hazelcast-session-replication`

so you can pass docker arguments to hazelcast.xml...

**Comment by jarosite** [comment]
works good for me, especially with <public-address> parameter

**Comment by bilalyasar** [comment]
currently it is working according to feedbacks and my tryings.
closing this issue, you can re-open if you encounter this problem again.
