### ISSUE TITLE
can't run docker hazelcast with provided example from documentation

### ISSUE THREAD

**Issue by Kydybets** [hazelcast/hazelcast-docker#132]
Hi,

i use next configuration to run in on my laptop for some investigation 
```
docker run -e JAVA_OPTS="-Dhazelcast.local.publicAddress=<my-laptop-ip>:5701" -itd -p 5701:5701 hazelcast/hazelcast
docker run -e JAVA_OPTS="-Dhazelcast.local.publicAddress=<my-laptop-ip>:5702" -itd -p 5702:5701 hazelcast/hazelcast
```

It starts ok, but once try to open it in the browser  I got next errors:
```
docker logs -ft a91ed298117a
2020-02-02T16:30:41.846203500Z ########################################
2020-02-02T16:30:41.846284000Z # JAVA_OPTS=-Dhazelcast.mancenter.enabled=false -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/opt/hazelcast/logging.properties -XX:MaxRAMPercentage=80.0 -Dhazelcast.local.publicAddress=192.168.1.227:5702
2020-02-02T16:30:41.846346700Z # CLASSPATH=/opt/hazelcast/*:/opt/hazelcast/lib/*
2020-02-02T16:30:41.846374200Z # starting now....
2020-02-02T16:30:41.846424700Z ########################################
2020-02-02T16:30:41.846467100Z + exec java -server -Dhazelcast.mancenter.enabled=false -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/opt/hazelcast/logging.properties -XX:MaxRAMPercentage=80.0 -Dhazelcast.local.publicAddress=192.168.1.227:5702 com.hazelcast.core.server.StartServer
2020-02-02T16:30:42.308056100Z Feb 02, 2020 4:30:42 PM com.hazelcast.config.AbstractConfigLocator
2020-02-02T16:30:42.308107500Z INFO: Loading 'hazelcast.xml' from the working directory.
2020-02-02T16:30:42.573693100Z Feb 02, 2020 4:30:42 PM com.hazelcast.config.ConfigReplacerHelper
2020-02-02T16:30:42.573739300Z WARNING: Could not find a replacement for '${hazelcast.mancenter.url}' on node 'null'
2020-02-02T16:30:42.589295500Z Feb 02, 2020 4:30:42 PM com.hazelcast.config.AbstractXmlConfigHelper
2020-02-02T16:30:42.589343400Z WARNING: Name of the hazelcast schema location is incorrect, using default
2020-02-02T16:30:43.080375300Z Feb 02, 2020 4:30:43 PM com.hazelcast.instance.AddressPicker
2020-02-02T16:30:43.080425900Z INFO: [LOCAL] [dev] [3.12.6] Prefer IPv4 stack is true, prefer IPv6 addresses is false
2020-02-02T16:30:43.125208000Z Feb 02, 2020 4:30:43 PM com.hazelcast.instance.AddressPicker
2020-02-02T16:30:43.125257000Z INFO: [LOCAL] [dev] [3.12.6] Picked [172.17.0.3]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
2020-02-02T16:30:43.127367400Z Feb 02, 2020 4:30:43 PM com.hazelcast.instance.AddressPicker
2020-02-02T16:30:43.127406000Z INFO: [LOCAL] [dev] [3.12.6] Using public address: [192.168.1.227]:5702
2020-02-02T16:30:43.178473000Z Feb 02, 2020 4:30:43 PM com.hazelcast.system
2020-02-02T16:30:43.178520900Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] Hazelcast 3.12.6 (20200130 - be02cc5) starting at [192.168.1.227]:5702
2020-02-02T16:30:43.179084500Z Feb 02, 2020 4:30:43 PM com.hazelcast.system
2020-02-02T16:30:43.179126400Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
2020-02-02T16:30:44.016255900Z Feb 02, 2020 4:30:44 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
2020-02-02T16:30:44.016298000Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] Backpressure is disabled
2020-02-02T16:30:45.447998900Z Feb 02, 2020 4:30:45 PM com.hazelcast.instance.Node
2020-02-02T16:30:45.448038100Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] Creating MulticastJoiner
2020-02-02T16:30:46.014734000Z Feb 02, 2020 4:30:46 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
2020-02-02T16:30:46.014791700Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tasks)
2020-02-02T16:30:46.027702300Z Feb 02, 2020 4:30:46 PM com.hazelcast.internal.diagnostics.Diagnostics
2020-02-02T16:30:46.027753900Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2020-02-02T16:30:46.054288500Z Feb 02, 2020 4:30:46 PM com.hazelcast.core.LifecycleService
2020-02-02T16:30:46.054323100Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] [192.168.1.227]:5702 is STARTING
2020-02-02T16:30:46.306238200Z Feb 02, 2020 4:30:46 PM com.hazelcast.internal.cluster.impl.MulticastJoiner
2020-02-02T16:30:46.306278300Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] Trying to join to discovered node: [192.168.1.227]:5701
2020-02-02T16:30:46.330212400Z Feb 02, 2020 4:30:46 PM com.hazelcast.nio.tcp.TcpIpConnector
2020-02-02T16:30:46.330252900Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] Connecting to /192.168.1.227:5701, timeout: 10000, bind-any: true
2020-02-02T16:30:46.525346400Z Feb 02, 2020 4:30:46 PM com.hazelcast.nio.tcp.TcpIpConnection
2020-02-02T16:30:46.525386900Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] Initialized new cluster connection between /172.17.0.3:45819 and /192.168.1.227:5701
2020-02-02T16:30:52.359924300Z Feb 02, 2020 4:30:52 PM com.hazelcast.internal.cluster.ClusterService
2020-02-02T16:30:52.360013700Z INFO: [192.168.1.227]:5702 [dev] [3.12.6]
2020-02-02T16:30:52.360040800Z
2020-02-02T16:30:52.360059500Z Members {size:2, ver:2} [
2020-02-02T16:30:52.360102700Z 	Member [192.168.1.227]:5701 - e152d11b-df3e-4c29-a363-188842fc624c
2020-02-02T16:30:52.360128200Z 	Member [192.168.1.227]:5702 - e7811c67-34ef-4ec5-9687-1945d7c36b69 this
2020-02-02T16:30:52.360159400Z ]
2020-02-02T16:30:52.360183200Z
2020-02-02T16:30:53.384531200Z Feb 02, 2020 4:30:53 PM com.hazelcast.core.LifecycleService
2020-02-02T16:30:53.384586000Z INFO: [192.168.1.227]:5702 [dev] [3.12.6] [192.168.1.227]:5702 is STARTED
2020-02-02T16:31:00.582731400Z Feb 02, 2020 4:31:00 PM com.hazelcast.nio.tcp.TcpIpConnection
2020-02-02T16:31:00.582871900Z WARNING: [192.168.1.227]:5702 [dev] [3.12.6] Connection[id=2, /172.17.0.3:5701->/172.17.0.1:60574, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=2, /172.17.0.3:5701->/172.17.0.1:60574, qualifier=null, endpoint=null, alive=true, type=NONE], thread=hz._hzInstance_1_dev.IO.thread-in-1
2020-02-02T16:31:00.582909200Z java.lang.IllegalStateException: REST API is not enabled.
2020-02-02T16:31:00.583013000Z 	at com.hazelcast.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:96)
2020-02-02T16:31:00.583049600Z 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135)
2020-02-02T16:31:00.583077900Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
2020-02-02T16:31:00.583122400Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
2020-02-02T16:31:00.583189100Z 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
2020-02-02T16:31:00.583220000Z 	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
2020-02-02T16:31:00.583249400Z
2020-02-02T16:31:00.604505300Z Feb 02, 2020 4:31:00 PM com.hazelcast.nio.tcp.TcpIpConnection
2020-02-02T16:31:00.604602100Z WARNING: [192.168.1.227]:5702 [dev] [3.12.6] Connection[id=3, /172.17.0.3:5701->/172.17.0.1:60576, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=3, /172.17.0.3:5701->/172.17.0.1:60576, qualifier=null, endpoint=null, alive=true, type=NONE], thread=hz._hzInstance_1_dev.IO.thread-in-2
2020-02-02T16:31:00.604632400Z java.lang.IllegalStateException: REST API is not enabled.
2020-02-02T16:31:00.604677200Z 	at com.hazelcast.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:96)
2020-02-02T16:31:00.604724100Z 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135)
2020-02-02T16:31:00.604758800Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
2020-02-02T16:31:00.604816500Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
2020-02-02T16:31:00.604849100Z 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
2020-02-02T16:31:00.604903500Z 	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
2020-02-02T16:31:00.604972000Z
2020-02-02T16:31:00.620053400Z Feb 02, 2020 4:31:00 PM com.hazelcast.nio.tcp.TcpIpConnection
2020-02-02T16:31:00.620134300Z WARNING: [192.168.1.227]:5702 [dev] [3.12.6] Connection[id=4, /172.17.0.3:5701->/172.17.0.1:60578, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=4, /172.17.0.3:5701->/172.17.0.1:60578, qualifier=null, endpoint=null, alive=true, type=NONE], thread=hz._hzInstance_1_dev.IO.thread-in-0
2020-02-02T16:31:00.620173700Z java.lang.IllegalStateException: REST API is not enabled.
2020-02-02T16:31:00.620242600Z 	at com.hazelcast.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:96)
2020-02-02T16:31:00.620315300Z 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135)
2020-02-02T16:31:00.620355000Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
2020-02-02T16:31:00.620390000Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
2020-02-02T16:31:00.620422800Z 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
2020-02-02T16:31:00.620456400Z 	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
2020-02-02T16:31:00.620509200Z
```

Could you please help me to understand where i goes wrong

**Comment by Kydybets** [comment]
sorry, everything is ok
