### ISSUE TITLE
not able to provide custom config file hazelcast.xml file

### ISSUE THREAD

**Issue by dhruv-bansal** [hazelcast/hazelcast-docker#88]
I am trying to run docker image with the following command
`docker run  -e JAVA_OPTS="-Dhazelcast.config=/Users/dhruvbansal/hazelcast.xml" hazelcast/hazelcast`

Getting following exception:

```
+ exec java -server -Djava.net.preferIPv4Stack=true -Dhazelcast.config=/Users/dhruvbansal/Documents/cafu/installers/hazelcast-3.10.4/bin com.hazelcast.core.server.StartServer
########################################
# JAVA_OPTS=-Djava.net.preferIPv4Stack=true -Dhazelcast.config=/Users/dhruvbansal/Documents/cafu/installers/hazelcast-3.10.4/bin
# CLASSPATH=/opt/hazelcast:/opt/hazelcast/*
# starting now....
########################################
Aug 23, 2018 7:55:18 AM com.hazelcast.config.XmlConfigLocator
INFO: Loading configuration /Users/dhruvbansal/Documents/cafu/installers/hazelcast-3.10.4/bin from System property 'hazelcast.config'
Aug 23, 2018 7:55:18 AM com.hazelcast.config.XmlConfigLocator
INFO: Using configuration file at /Users/dhruvbansal/Documents/cafu/installers/hazelcast-3.10.4/bin
Exception in thread "main" com.hazelcast.core.HazelcastException: com.hazelcast.core.HazelcastException: Config file at '/Users/dhruvbansal/hazelcast.xml' doesn't exist.
	at com.hazelcast.config.XmlConfigLocator.<init>(XmlConfigLocator.java:68)
	at com.hazelcast.config.XmlConfigBuilder.<init>(XmlConfigBuilder.java:179)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:122)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at com.hazelcast.core.server.StartServer.main(StartServer.java:46)
Caused by: com.hazelcast.core.HazelcastException: Config file at '/Users/dhruvbansal/Documents/cafu/installers/hazelcast-3.10.4/bin' doesn't exist.
	at com.hazelcast.config.XmlConfigLocator.loadSystemPropertyFileResource(XmlConfigLocator.java:160)
	at com.hazelcast.config.XmlConfigLocator.loadFromSystemProperty(XmlConfigLocator.java:148)
	at com.hazelcast.config.XmlConfigLocator.<init>(XmlConfigLocator.java:54)
	... 4 more

```
File at /Users/dhruvbansal/hazelcast.xml is present and valid.

**Comment by leszko** [comment]
@dhruv-bansal Please check [1]. In order to use custom configuration, you need to either: mount a volume or build your own image.

In your case, the path is not accessible inside the container, so Hazelcast can't access it.

[1] https://github.com/hazelcast/hazelcast-docker#using-custom-hazelcast-configuration-file

**Comment by leszko** [comment]
Closing because of inactivity. Feel free to reopen if needed.
